Math magicians 2nd milestone
marcosmerida/math-magicians pull request #3
Opened 2021-10-26 22:44 UTC by marcosmerida

- React set up.
- React components.
- webpack.
- CSS.

2021-10-26 23:28 UTC, eliasecasta requested changes
# Status:  Changes Required ♻️
_Check the comments under the review_
<hr>

Hello @marcosmerida, I am Elias, your reviewer for this PR

Well done so far with your project!

Your calculator design looks amazing! I would only suggest you make it bigger.

I will mention to you a small summary of things that need to be changed in order to keep moving:

- [x] Please use the Microverse template readme given to you for this milestone, currently, you are using the one provided by React but it is needed for this milestone to have all the project information necessary.
- [x] Please remove all the boilerplate files (react logos, favicon and the index.css file) in order to comply with the project requirements.
- [x] Please check below for extra requirements in this PR.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [x] Please make your calculator bigger to make it look better and easier to use.

Please correct those issues and send another review request, good luck, and well done so far! 

Code review by Elias Castañeda

_(Feel free to leave any questions or comments in the PR thread if something is not 100% clear)_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/restricted?return_to=https%3A%2F%2Fmicroverse.zendesk.com%2Fhc%2Fen-us%2Farticles%2F1500004088561) you have a limited number of code reviews per project (you can check the exact number in your Dashboard). If you think that the code review was not fair, you can [request a second opinion using this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-10-26 23:28 UTC, eliasecasta commented on src/component/Calculator.js
> +function Calculator() {
- [x] The `Calculator.js` component should be class-based, please refactor it to comply with the project requirements.

2021-10-26 23:28 UTC, eliasecasta commented on src/App.js
>  function App() {
- [x] The `App.js` component should be class-based, please refactor it to comply with the project requirements.

2021-10-27 00:45 UTC, Davidosky007 commented
## Hi @marcosmerida 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
* As the previous reviewer stated that all boilerplate files be removed your folder still has some boilerplate file 
![image](https://user-images.githubusercontent.com/52497246/138981206-f763b839-001a-4dd0-88b6-dd0219a2e506.png)

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-27 01:01 UTC, eliasecasta approved these changes
## Status:  Approved 🟢

Hi, @marcosmerida, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

![](https://media3.giphy.com/media/DnMMGxEvniha7CvASq/giphy.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-27 16:44 UTC, merged